// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: proxyGrpc.proto

package proxyGrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientSendRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid          string `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	AttributeSet string `protobuf:"bytes,2,opt,name=attributeSet,proto3" json:"attributeSet,omitempty"`
	PubKey       string `protobuf:"bytes,3,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
}

func (x *ClientSendRequest) Reset() {
	*x = ClientSendRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proxyGrpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientSendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSendRequest) ProtoMessage() {}

func (x *ClientSendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proxyGrpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSendRequest.ProtoReflect.Descriptor instead.
func (*ClientSendRequest) Descriptor() ([]byte, []int) {
	return file_proxyGrpc_proto_rawDescGZIP(), []int{0}
}

func (x *ClientSendRequest) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *ClientSendRequest) GetAttributeSet() string {
	if x != nil {
		return x.AttributeSet
	}
	return ""
}

func (x *ClientSendRequest) GetPubKey() string {
	if x != nil {
		return x.PubKey
	}
	return ""
}

type ClientReceiveReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewCapsule  string `protobuf:"bytes,1,opt,name=newCapsule,proto3" json:"newCapsule,omitempty"`
	ReEncpubKey string `protobuf:"bytes,2,opt,name=reEncpubKey,proto3" json:"reEncpubKey,omitempty"`
	CipherText  string `protobuf:"bytes,3,opt,name=cipherText,proto3" json:"cipherText,omitempty"`
}

func (x *ClientReceiveReply) Reset() {
	*x = ClientReceiveReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proxyGrpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientReceiveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientReceiveReply) ProtoMessage() {}

func (x *ClientReceiveReply) ProtoReflect() protoreflect.Message {
	mi := &file_proxyGrpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientReceiveReply.ProtoReflect.Descriptor instead.
func (*ClientReceiveReply) Descriptor() ([]byte, []int) {
	return file_proxyGrpc_proto_rawDescGZIP(), []int{1}
}

func (x *ClientReceiveReply) GetNewCapsule() string {
	if x != nil {
		return x.NewCapsule
	}
	return ""
}

func (x *ClientReceiveReply) GetReEncpubKey() string {
	if x != nil {
		return x.ReEncpubKey
	}
	return ""
}

func (x *ClientReceiveReply) GetCipherText() string {
	if x != nil {
		return x.CipherText
	}
	return ""
}

type ProxyNodeSendRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AttributeSet string `protobuf:"bytes,1,opt,name=attributeSet,proto3" json:"attributeSet,omitempty"`
	ClientPubKey string `protobuf:"bytes,2,opt,name=clientPubKey,proto3" json:"clientPubKey,omitempty"`
}

func (x *ProxyNodeSendRequest) Reset() {
	*x = ProxyNodeSendRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proxyGrpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProxyNodeSendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyNodeSendRequest) ProtoMessage() {}

func (x *ProxyNodeSendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proxyGrpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyNodeSendRequest.ProtoReflect.Descriptor instead.
func (*ProxyNodeSendRequest) Descriptor() ([]byte, []int) {
	return file_proxyGrpc_proto_rawDescGZIP(), []int{2}
}

func (x *ProxyNodeSendRequest) GetAttributeSet() string {
	if x != nil {
		return x.AttributeSet
	}
	return ""
}

func (x *ProxyNodeSendRequest) GetClientPubKey() string {
	if x != nil {
		return x.ClientPubKey
	}
	return ""
}

type ProxyNodeReceiveReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReEncKey    string `protobuf:"bytes,1,opt,name=reEncKey,proto3" json:"reEncKey,omitempty"`
	ReEncPubKey string `protobuf:"bytes,2,opt,name=reEncPubKey,proto3" json:"reEncPubKey,omitempty"`
	CipherText  string `protobuf:"bytes,3,opt,name=cipherText,proto3" json:"cipherText,omitempty"`
	Capsule     string `protobuf:"bytes,4,opt,name=capsule,proto3" json:"capsule,omitempty"`
}

func (x *ProxyNodeReceiveReply) Reset() {
	*x = ProxyNodeReceiveReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proxyGrpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProxyNodeReceiveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyNodeReceiveReply) ProtoMessage() {}

func (x *ProxyNodeReceiveReply) ProtoReflect() protoreflect.Message {
	mi := &file_proxyGrpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyNodeReceiveReply.ProtoReflect.Descriptor instead.
func (*ProxyNodeReceiveReply) Descriptor() ([]byte, []int) {
	return file_proxyGrpc_proto_rawDescGZIP(), []int{3}
}

func (x *ProxyNodeReceiveReply) GetReEncKey() string {
	if x != nil {
		return x.ReEncKey
	}
	return ""
}

func (x *ProxyNodeReceiveReply) GetReEncPubKey() string {
	if x != nil {
		return x.ReEncPubKey
	}
	return ""
}

func (x *ProxyNodeReceiveReply) GetCipherText() string {
	if x != nil {
		return x.CipherText
	}
	return ""
}

func (x *ProxyNodeReceiveReply) GetCapsule() string {
	if x != nil {
		return x.Capsule
	}
	return ""
}

var File_proxyGrpc_proto protoreflect.FileDescriptor

var file_proxyGrpc_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x47, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x47, 0x72, 0x70, 0x63, 0x22, 0x61, 0x0a, 0x11,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x63, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x53, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x74, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x65, 0x53, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x75, 0x62, 0x4b, 0x65,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x22,
	0x76, 0x0a, 0x12, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x6e, 0x65, 0x77, 0x43, 0x61, 0x70, 0x73,
	0x75, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x65, 0x77, 0x43, 0x61,
	0x70, 0x73, 0x75, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x45, 0x6e, 0x63, 0x70, 0x75,
	0x62, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x45, 0x6e,
	0x63, 0x70, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x69, 0x70, 0x68, 0x65,
	0x72, 0x54, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x69, 0x70,
	0x68, 0x65, 0x72, 0x54, 0x65, 0x78, 0x74, 0x22, 0x5e, 0x0a, 0x14, 0x50, 0x72, 0x6f, 0x78, 0x79,
	0x4e, 0x6f, 0x64, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x22, 0x0a, 0x0c, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x53, 0x65, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x53, 0x65, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50, 0x75, 0x62,
	0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x22, 0x8f, 0x01, 0x0a, 0x15, 0x50, 0x72, 0x6f, 0x78,
	0x79, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x45, 0x6e, 0x63, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x45, 0x6e, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x20, 0x0a,
	0x0b, 0x72, 0x65, 0x45, 0x6e, 0x63, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x45, 0x6e, 0x63, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x12,
	0x1e, 0x0a, 0x0a, 0x63, 0x69, 0x70, 0x68, 0x65, 0x72, 0x54, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x69, 0x70, 0x68, 0x65, 0x72, 0x54, 0x65, 0x78, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x61, 0x70, 0x73, 0x75, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x61, 0x70, 0x73, 0x75, 0x6c, 0x65, 0x32, 0xbc, 0x01, 0x0a, 0x07, 0x47, 0x72,
	0x65, 0x65, 0x74, 0x65, 0x72, 0x12, 0x56, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x41, 0x74, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x43, 0x69, 0x70, 0x68, 0x65, 0x72, 0x12, 0x1c,
	0x2e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x47, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70,
	0x72, 0x6f, 0x78, 0x79, 0x47, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x59, 0x0a,
	0x12, 0x47, 0x65, 0x74, 0x52, 0x65, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x4b, 0x65, 0x79, 0x12, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x47, 0x72, 0x70, 0x63, 0x2e,
	0x50, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x47, 0x72, 0x70, 0x63,
	0x2e, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f, 0x53, 0x41, 0x43, 0x32,
	0x34, 0x2f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x47, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proxyGrpc_proto_rawDescOnce sync.Once
	file_proxyGrpc_proto_rawDescData = file_proxyGrpc_proto_rawDesc
)

func file_proxyGrpc_proto_rawDescGZIP() []byte {
	file_proxyGrpc_proto_rawDescOnce.Do(func() {
		file_proxyGrpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_proxyGrpc_proto_rawDescData)
	})
	return file_proxyGrpc_proto_rawDescData
}

var file_proxyGrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proxyGrpc_proto_goTypes = []interface{}{
	(*ClientSendRequest)(nil),     // 0: proxyGrpc.ClientSendRequest
	(*ClientReceiveReply)(nil),    // 1: proxyGrpc.ClientReceiveReply
	(*ProxyNodeSendRequest)(nil),  // 2: proxyGrpc.ProxyNodeSendRequest
	(*ProxyNodeReceiveReply)(nil), // 3: proxyGrpc.ProxyNodeReceiveReply
}
var file_proxyGrpc_proto_depIdxs = []int32{
	0, // 0: proxyGrpc.Greeter.GetAttributeKeyCipher:input_type -> proxyGrpc.ClientSendRequest
	2, // 1: proxyGrpc.Greeter.GetReEncryptionKey:input_type -> proxyGrpc.ProxyNodeSendRequest
	1, // 2: proxyGrpc.Greeter.GetAttributeKeyCipher:output_type -> proxyGrpc.ClientReceiveReply
	3, // 3: proxyGrpc.Greeter.GetReEncryptionKey:output_type -> proxyGrpc.ProxyNodeReceiveReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proxyGrpc_proto_init() }
func file_proxyGrpc_proto_init() {
	if File_proxyGrpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proxyGrpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientSendRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proxyGrpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientReceiveReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proxyGrpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProxyNodeSendRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proxyGrpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProxyNodeReceiveReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proxyGrpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proxyGrpc_proto_goTypes,
		DependencyIndexes: file_proxyGrpc_proto_depIdxs,
		MessageInfos:      file_proxyGrpc_proto_msgTypes,
	}.Build()
	File_proxyGrpc_proto = out.File
	file_proxyGrpc_proto_rawDesc = nil
	file_proxyGrpc_proto_goTypes = nil
	file_proxyGrpc_proto_depIdxs = nil
}
